/**************** DO NOT TOUCH *****************/
/* This file gets generated by 'env:*' scripts */
/***********************************************/

export default {
  API_URL: "https://api.carejo-dev.com",
  ENV: "development",
  HEADER_AUTH: "dijero",
  WEB_URL: "https://www.carejo-dev.com",
};
